export const data = [
  {
    movie_name: "A Ring of Endless Light",
    image_url: "/images/a-ring-of-endless-light.png",
    watched: false,
    current: false,
  },
  {
    movie_name: "Adventures in Babysitting",
    image_url: "/images/adventures-in-babysitting.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Alley Cats Strike",
    image_url: "/images/alley-cats-strike.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Avalon High",
    image_url: "/images/avalon-high.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Bad Hair Day",
    image_url: "/images/bad-hair-day.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Brink!",
    image_url: "/images/brink.png",
    watched: true,
    current: false,
  },
  {
    movie_name: "Buffalo Dreams",
    image_url: "/images/buffalo-dreams.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Cadet Kelly",
    image_url: "/images/cadet-kelly.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Camp Rock",
    image_url: "/images/camp-rock.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Camp Rock 2: The Final Jam",
    image_url: "/images/camp-rock-2.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Can of Worms",
    image_url: "/images/can-of-worms.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Christmas... Again?!",
    image_url: "/images/christmas-again.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Cloud 9",
    image_url: "/images/cloud-9.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Cow Belles",
    image_url: "/images/cow-belles.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Dadnapped",
    image_url: "/images/dadnapped.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Den Brother",
    image_url: "/images/den-brother.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Descendants",
    image_url: "/images/descendants.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Descendants 2",
    image_url: "/images/descendants-2.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Descendants 3",
    image_url: "/images/descendants-3.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Don't Look Under the Bed",
    image_url: "/images/dont-look-under-the-bed.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Double Teamed",
    image_url: "/images/double-teamed.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Eddie's Million Dollar Cook-Off",
    image_url: "/images/eddies-million-dollar-cook-off.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Freaky Friday",
    image_url: "/images/freaky-friday.jpeg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Frenemies",
    image_url: "/images/frenemies.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Full-Court Miracle",
    image_url: "/images/full-court-miracle.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Geek Charming",
    image_url: "/images/geek-charming.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Genius",
    image_url: "/images/genius.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Get a Clue",
    image_url: "/images/get-a-clue.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Girl vs. Monster",
    image_url: "/images/girl-vs-monster.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Go Figure",
    image_url: "/images/go-figure.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Going to the Mat",
    image_url: "/images/going-to-the-mat.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Good Luck Charlie, It's Christmas!",
    image_url: "/images/good-luck-charlie-its-christmas.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Gotta Kick It Up!",
    image_url: "/images/gotta-kick-it-up.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Halloweentown",
    image_url: "/images/halloweentown.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Halloweentown High",
    image_url: "/images/halloweentown-high.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Halloweentown II: Kalabar's Revenge",
    image_url: "/images/halloweentown-two.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Hatching Pete",
    image_url: "/images/hatching-pete.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "High School Musical",
    image_url: "/images/high-school-musical.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "High School Musical 2",
    image_url: "/images/high-school-musical-2.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Horse Sense",
    image_url: "/images/horse-sense.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Hounded",
    image_url: "/images/hounded.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "How to Build a Better Boy",
    image_url: "/images/how-to-build-a-better-boy.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Invisible Sister",
    image_url: "/images/invisible-sister.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Jett Jackson: The Movie",
    image_url: "/images/jett-jackson-the-movie.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Johnny Kapahala: Back on Board",
    image_url: "/images/johnny-kapahala-back-on-board.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Johnny Tsunami",
    image_url: "/images/johnny-tsunami.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Jump In!",
    image_url: "/images/jump-in.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Jumping Ship",
    image_url: "/images/jumping-ship.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Kim Possible",
    image_url: "/images/kim-possible.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Kim Possible Movie: So the Drama",
    image_url: "/images/kim-possible-so-the-drama.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Lemonade Mouth",
    image_url: "/images/lemonade-mouth.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Let It Shine",
    image_url: "/images/let-it-shine.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Life Is Ruff",
    image_url: "/images/life-is-ruff.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Minutemen",
    image_url: "/images/minutemen.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Miracle in Lane 2",
    image_url: "/images/miracle-in-lane-2.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Mom's Got a Date with a Vampire",
    image_url: "/images/moms-got-a-date-with-a-vampire.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Motocrossed",
    image_url: "/images/motocrossed.JPG",
    watched: true,
    current: false,
  },
  {
    movie_name: "Now You See It...",
    image_url: "/images/now-you-see-it.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Phantom of the Megaplex",
    image_url: "/images/phantom-of-the-megaplex.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Phineas and Ferb the Movie: Across the 2nd Dimension",
    image_url: "/images/phineas-and-ferb.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Pixel Perfect",
    image_url: "/images/pixel-perfect.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Princess Protection Program",
    image_url: "/images/princess-protection-program.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Quints",
    image_url: "/images/quints.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Radio Rebel",
    image_url: "/images/radio-rebel.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Read It and Weep",
    image_url: "/images/read-it-and-weep.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Ready to Run",
    image_url: "/images/ready-to-run.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Return to Halloweentown",
    image_url: "/images/return-to-halloweentown.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Right on Track",
    image_url: "/images/right-on-track.png",
    watched: false,
    current: false,
  },
  {
    movie_name: "Rip Girls",
    image_url: "/images/rip-girls.jpeg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Sharpay's Fabulous Adventure",
    image_url: "/images/sharpay.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Smart House",
    image_url: "/images/smart-house.png",
    watched: true,
    current: false,
  },
  {
    movie_name: "Spin",
    image_url: "/images/spin.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Starstruck",
    image_url: "/images/starstruck.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Stepsister from Planet Weird",
    image_url: "/images/stepsister-from-planet-weird.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Stuck in the Suburbs",
    image_url: "/images/stuck-in-the-suburbs.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Tangled: Before Ever After",
    image_url: "/images/tangled.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Teen Beach Movie",
    image_url: "/images/teen-beach-movie.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Teen Beach 2",
    image_url: "/images/teen-beach-movie-two.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Cheetah Girls",
    image_url: "/images/the-cheetah-girls.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Cheetah Girls 2",
    image_url: "/images/the-cheetah-girls-two.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Cheetah Girls: One World",
    image_url: "/images/the-cheetah-girls-one-world.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Color of Friendship",
    image_url: "/images/the-color-of-friendship.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Even Stevens Movie",
    image_url: "/images/the-even-stevens-movie.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Jennie Project",
    image_url: "/images/the-jennie-project.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Luck of the Irish",
    image_url: "/images/the-luck-of-the-irish.png",
    watched: true,
    current: false,
  },
  {
    movie_name: "The Other Me",
    image_url: "/images/the-other-me.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Poof Point",
    image_url: "/images/the-poof-point.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Proud Family Movie",
    image_url: "/images/the-proud-family.jpeg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Scream Team",
    image_url: "/images/the-scream-team.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Suite Life Movie",
    image_url: "/images/the-suite-life-movie.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Swap",
    image_url: "/images/the-swap.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "The Thirteenth Year",
    image_url: "/images/the-thirteenth-year.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "The Ultimate Christmas Present",
    image_url: "/images/the-ultimate-christmas-present.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Tiger Cruise",
    image_url: "/images/tiger-cruise.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Tru Confessions",
    image_url: "/images/tru-confessions.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Twas the Night",
    image_url: "/images/twas-the-night.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Twitches",
    image_url: "/images/twitches.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Twitches Too",
    image_url: "/images/twitches-too.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Under Wraps",
    image_url: "/images/under-wraps.png",
    watched: false,
    current: false,
  },
  {
    movie_name: "Up, Up, and Away",
    image_url: "/images/up-up-and-away.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Upside-Down Magic",
    image_url: "/images/upside-down-magic.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Wendy Wu: Homecoming Warrior",
    image_url: "/images/wendy-wu.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Wizards of Waverly Place: The Movie",
    image_url: "/images/wizards-of-waverly-place.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "You Lucky Dog",
    image_url: "/images/you-lucky-dog.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "You Wish!",
    image_url: "/images/you-wish.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Zapped",
    image_url: "/images/zapped.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Zenon: Girl of the 21st Century",
    image_url: "/images/zenon.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Zenon: The Zequel",
    image_url: "/images/zenon-the-zequel.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Zenon: Z3",
    image_url: "/images/zenon-z3.jpg",
    watched: true,
    current: false,
  },
  {
    movie_name: "Zombies",
    image_url: "/images/zombies.jpg",
    watched: false,
    current: false,
  },
  {
    movie_name: "Zombies 2",
    image_url: "/images/zombies-2.jpg",
    watched: false,
    current: false,
  },
];
